spring:
  redis:
    host: 192.168.56.100
    port: 6379
    #    因为SpringBoot2.x使用的Lettuce作为连接Redis的客户端，所以我们配置Lettuce的连接池配置
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
        max-wait: 10000

